DROP TABLE IF EXISTS music_data;

CREATE TABLE music_data (
    idade TEXT,
    genero TEXT,
    regiao TEXT,
    genero_favorito TEXT,
    generos_escuta TEXT,
    generos_evita TEXT,
    motivo_gostar TEXT,
    motivo_nao_gostar TEXT,
    variedade_generos TEXT,
    tempo_escuta TEXT,
    plataforma_descoberta TEXT,
    frequencia_descoberta TEXT,
    preferencia_nacional TEXT
);
INSERT INTO music_data VALUES ('16-18', 'Masculino', 'Sudeste', 'Rock/Metal', 'Rap/Trap/Hip Hop, Rock/Metal, Pagode/Samba, Indie/Alternativo', 'Funk', 'Emoção que transmite', 'Letra', 'Vários gêneros', '2-4 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('19-24', 'Masculino', 'Sudeste', 'MPB', 'Pop, MPB, Jazz/Blues, Clássica/Instrumental', 'Sertanejo/Sertanejo Universitário, Gospel/Religiosa', 'Ritmo/Instrumental/Beat', 'Ritmo/Instrumental/Beat', 'Poucos gêneros', '2-4 horas', 'Youtube', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('19-24', 'Masculino', 'Nordeste', 'Rock/Metal', 'Rock/Metal, Pop, MPB, Latina/Reggaeton/Dembow/Salsa, Forró/Piseiro/Brega, Indie/Alternativo, Clássica/Instrumental', 'Funk, Rap/Trap/HipHop', 'Emoção que transmite', 'Não me identifico', 'Poucos gêneros', '1-2 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('19-24', 'Outro', 'Sudeste', 'Rock/Metal', 'Rap/Trap/Hip Hop, Rock/Metal, Indie/Alternativo, Jazz/Blues', 'Funk, Forró/Piseiro/Brega', 'Ritmo/Instrumental/Beat', 'Letra', 'Vários gêneros', 'Mais de 4 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('16-18', 'Masculino', 'Não moro no Brasil', 'Indie/Alternativo', 'Funk, Rap/Trap/Hip Hop, Rock/Metal, Pop, Eletrônica/Dubstep/Techno/EDM, MPB, Pagode/Samba, Latina/Reggaeton/Dembow/Salsa, Indie/Alternativo, Jazz/Blues, Clássica/Instrumental', 'Sertanejo/Sertanejo Universitário, Gospel/Religiosa', 'Ritmo/Instrumental/Beat', 'Ritmo/Instrumental/Beat', 'Vários gêneros', 'Mais de 4 horas', 'Amigos/Familiares', 'Frequentemente', 'Ambos');
INSERT INTO music_data VALUES ('16-18', 'Prefiro não informar', 'Norte', 'Rock/Metal', 'Pop', 'Funk', 'Ritmo/Instrumental/Beat', 'Não gosto dos artistas do gênero', 'Vários gêneros', 'Mais de 4 horas', 'Youtube', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('19-24', 'Masculino', 'Sudeste', 'Rock/Metal', 'Rock/Metal, Pop, Gospel/Religiosa, Indie/Alternativo, Clássica/Instrumental', 'Sertanejo/Sertanejo Universitário, Funk, Rap/Trap/HipHop, Latina/Reggaeton/Dembow/Salsa', 'Ritmo/Instrumental/Beat', 'Influência religiosa', 'Vários gêneros', 'Mais de 4 horas', 'Youtube', 'As vezes', 'Internacionais');
INSERT INTO music_data VALUES ('16-18', 'Feminino', 'Centro-Oeste', 'Pop', 'Sertanejo/Sertanejo Universitário, Rap/Trap/Hip Hop, Pop, MPB', 'Rock/Metal, Eletrônica/Dubstep/Techno/EDM, Gospel/Religiosa, Latina/Reggaeton/Dembow/Salsa, Forró/Piseiro/Brega', 'Emoção que transmite', 'Não gosto dos artistas do gênero', 'Vários gêneros', '1-2 horas', 'Tiktok', 'Frequentemente', 'Internacionais');
INSERT INTO music_data VALUES ('19-24', 'Feminino', 'Sudeste', 'Indie/Alternativo', 'Pop, Eletrônica/Dubstep/Techno/EDM, Indie/Alternativo, Jazz/Blues, Clássica/Instrumental', 'Sertanejo/Sertanejo Universitário, Pagode/Samba', 'Ritmo/Instrumental/Beat', 'Não me identifico', 'Vários gêneros', '2-4 horas', 'Youtube', 'Frequentemente', 'Ambos');
INSERT INTO music_data VALUES ('16-18', 'Feminino', 'Centro-Oeste', 'Indie/Alternativo', 'Sertanejo/Sertanejo Universitário, Funk, Pop, Indie/Alternativo', 'Eletrônica/Dubstep/Techno/EDM', 'Emoção que transmite', 'Não me identifico', 'Vários gêneros', 'Menos de 1 hora por dia', 'Tiktok', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('16-18', 'Feminino', 'Centro-Oeste', 'Latina/Reggaeton/Dembow/Salsa', 'Funk, Rap/Trap/Hip Hop, Pop, MPB, Pagode/Samba, Latina/Reggaeton/Dembow/Salsa, Forró/Piseiro/Brega, Jazz/Blues, Clássica/Instrumental', 'Gospel/Religiosa', 'Emoção que transmite', 'Não me identifico', 'Vários gêneros', '1-2 horas', 'Tiktok', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('16-18', 'Masculino', 'Centro-Oeste', 'Funk', 'Sertanejo/Sertanejo Universitário, Funk, Rap/Trap/Hip Hop, Pop, Pagode/Samba, Forró/Piseiro/Brega', 'MPB, Jazz/Blues', 'Ritmo/Instrumental/Beat', 'Ritmo/Instrumental/Beat', 'Vários gêneros', '2-4 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'As vezes', 'Nacionais');
INSERT INTO music_data VALUES ('16-18', 'Masculino', 'Centro-Oeste', 'Rap/Trap/Hip Hop', 'Funk, Rap/Trap/Hip Hop, Rock/Metal, Pop, MPB, Latina/Reggaeton/Dembow/Salsa, Indie/Alternativo', 'Eletrônica/Dubstep/Techno/EDM, Gospel/Religiosa', 'Emoção que transmite', 'Influência religiosa', 'Vários gêneros', 'Mais de 4 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'Frequentemente', 'Ambos');
INSERT INTO music_data VALUES ('16-18', 'Masculino', 'Centro-Oeste', 'Pagode/Samba', 'Rap/Trap/Hip Hop, Rock/Metal, Pop, Pagode/Samba, Jazz/Blues', 'Sertanejo/Sertanejo Universitário, Funk, Forró/Piseiro/Brega', 'Ritmo/Instrumental/Beat', 'Letra', 'Poucos gêneros', '2-4 horas', 'Youtube', 'As vezes', 'Nacionais');
INSERT INTO music_data VALUES ('16-18', 'Feminino', 'Centro-Oeste', 'Pop', 'Rap/Trap/Hip Hop, Pop, MPB, Latina/Reggaeton/Dembow/Salsa, Indie/Alternativo', 'Sertanejo/Sertanejo Universitário', 'Ritmo/Instrumental/Beat', 'Não me identifico', 'Vários gêneros', '2-4 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'Frequentemente', 'Nacionais');
INSERT INTO music_data VALUES ('16-18', 'Masculino', 'Centro-Oeste', 'Clássica/Instrumental', 'Rap/Trap/Hip Hop', 'Gospel/Religiosa, Latina/Reggaeton/Dembow/Salsa', 'Ritmo/Instrumental/Beat', 'Não me identifico', 'Vários gêneros', 'Mais de 4 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'Frequentemente', 'Ambos');
INSERT INTO music_data VALUES ('16-18', 'Feminino', 'Centro-Oeste', 'Pop', 'Funk, Rock/Metal, Pop, Eletrônica/Dubstep/Techno/EDM, MPB, Indie/Alternativo', 'Sertanejo/Sertanejo Universitário, Rap/Trap/HipHop, Gospel/Religiosa', 'Emoção que transmite', 'Não me identifico', 'Vários gêneros', '2-4 horas', 'Tiktok', 'Frequentemente', 'Ambos');
INSERT INTO music_data VALUES ('35-44', 'Feminino', 'Centro-Oeste', 'Pagode/Samba', 'Funk', 'Eletrônica/Dubstep/Techno/EDM', 'Letra', 'Letra', 'Vários gêneros', '2-4 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'Frequentemente', 'Nacionais');
INSERT INTO music_data VALUES ('45+', 'Feminino', 'Centro-Oeste', 'Sertanejo/Sertanejo Universitário', 'Sertanejo/Sertanejo Universitário', 'Funk', 'Emoção que transmite', 'Não me identifico', 'Vários gêneros', 'Menos de 1 hora por dia', 'Spotify, Apple Music e outras plataformas musicais.', 'As vezes', 'Nacionais');
INSERT INTO music_data VALUES ('25-34', 'Feminino', 'Centro-Oeste', 'Sertanejo/Sertanejo Universitário', 'Sertanejo/Sertanejo Universitário, Pagode/Samba', 'Rock/Metal', 'Letra', 'Letra', 'Vários gêneros', '1-2 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'As vezes', 'Nacionais');
INSERT INTO music_data VALUES ('16-18', 'Feminino', 'Centro-Oeste', 'Gospel/Religiosa', 'Pop, Gospel/Religiosa, Clássica/Instrumental', 'Funk, Rap/Trap/HipHop, Rock/Metal', 'Letra', 'Não me identifico', 'Poucos gêneros', '1-2 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('45+', 'Masculino', 'Sudeste', 'Rock/Metal', 'Rock/Metal', 'Sertanejo/Sertanejo Universitário, Funk, Eletrônica/Dubstep/Techno/EDM, Pagode/Samba, Latina/Reggaeton/Dembow/Salsa, Forró/Piseiro/Brega', 'Ritmo/Instrumental/Beat', 'Não me identifico', 'Poucos gêneros', 'Menos de 1 hora por dia', 'Spotify, Apple Music e outras plataformas musicais.', 'Raramente', 'Ambos');
INSERT INTO music_data VALUES ('16-18', 'Feminino', 'Centro-Oeste', 'Sertanejo/Sertanejo Universitário', 'Sertanejo/Sertanejo Universitário, Funk, Eletrônica/Dubstep/Techno/EDM', 'Rock/Metal', 'Ritmo/Instrumental/Beat', 'Não me identifico', 'Vários gêneros', '2-4 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'Frequentemente', 'Ambos');
INSERT INTO music_data VALUES ('16-18', 'Masculino', 'Centro-Oeste', 'Sertanejo/Sertanejo Universitário', 'Sertanejo/Sertanejo Universitário, Rap/Trap/Hip Hop', 'Rock/Metal', 'Ritmo/Instrumental/Beat', 'Letra', 'Vários gêneros', '1-2 horas', 'Tiktok', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('16-18', 'Feminino', 'Centro-Oeste', 'MPB', 'Sertanejo/Sertanejo Universitário, Funk, Rap/Trap/Hip Hop, Latina/Reggaeton/Dembow/Salsa, Jazz/Blues', 'Rock/Metal, Clássica/Instrumental', 'Letra', 'Influência religiosa', 'Vários gêneros', '2-4 horas', 'Tiktok', 'As vezes', 'Internacionais');
INSERT INTO music_data VALUES ('16-18', 'Feminino', 'Centro-Oeste', 'Rap/Trap/Hip Hop', 'Rap/Trap/Hip Hop, Gospel/Religiosa, MPB', 'Rock/Metal, Indie/Alternativo', 'Emoção que transmite', 'Não me identifico', 'Poucos gêneros', '1-2 horas', 'Tiktok', 'As vezes', 'Nacionais');
INSERT INTO music_data VALUES ('45+', 'Feminino', 'Centro-Oeste', 'MPB', 'MPB', 'MPB', 'Letra', 'Letra', 'Vários gêneros', '2-4 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('16-18', 'Feminino', 'Centro-Oeste', 'Sertanejo/Sertanejo Universitário', 'Sertanejo/Sertanejo Universitário, Funk, Forró/Piseiro/Brega', 'Rap/Trap/HipHop, Rock/Metal, Eletrônica/Dubstep/Techno/EDM, Indie/Alternativo, Jazz/Blues', 'Emoção que transmite', 'Não me identifico', 'Vários gêneros', '2-4 horas', 'Tiktok', 'Frequentemente', 'Ambos');
INSERT INTO music_data VALUES ('25-34', 'Feminino', 'Sudeste', 'Rock/Metal', 'Rock/Metal, Pop, Eletrônica/Dubstep/Techno/EDM, MPB', 'Sertanejo/Sertanejo Universitário, Funk, Forró/Piseiro/Brega', 'Ritmo/Instrumental/Beat', 'Ritmo/Instrumental/Beat', 'Vários gêneros', 'Mais de 4 horas', 'Youtube', 'Frequentemente', 'Internacionais');
INSERT INTO music_data VALUES ('16-18', 'Feminino', 'Centro-Oeste', 'Pop', 'Rock/Metal, Pop, MPB, Indie/Alternativo, Jazz/Blues', 'Sertanejo/Sertanejo Universitário, Rap/Trap/HipHop, Gospel/Religiosa', 'Ritmo/Instrumental/Beat', 'Não me identifico', 'Vários gêneros', 'Menos de 1 hora por dia', 'Tiktok', 'Raramente', 'Ambos');
INSERT INTO music_data VALUES ('15 anos ou menos', 'Feminino', 'Centro-Oeste', 'Sertanejo/Sertanejo Universitário', 'Sertanejo/Sertanejo Universitário, Funk, Gospel/Religiosa, Pagode/Samba', 'Rock/Metal', 'Ritmo/Instrumental/Beat', 'Não me identifico', 'Poucos gêneros', '1-2 horas', 'Tiktok', 'Raramente', 'Nacionais');
INSERT INTO music_data VALUES ('16-18', 'Feminino', 'Centro-Oeste', 'Rap/Trap/Hip Hop', 'Rap/Trap/Hip Hop, Pop', 'MPB', 'Ritmo/Instrumental/Beat', 'Ritmo/Instrumental/Beat', 'Vários gêneros', '1-2 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'Frequentemente', 'Internacionais');
INSERT INTO music_data VALUES ('16-18', 'Feminino', 'Centro-Oeste', 'Gospel/Religiosa', 'Pop, Eletrônica/Dubstep/Techno/EDM, Latina/Reggaeton/Dembow/Salsa, Clássica/Instrumental', 'Funk, Rock/Metal, Indie/Alternativo', 'Letra', 'Não gosto dos artistas do gênero', 'Poucos gêneros', 'Menos de 1 hora por dia', 'Tiktok', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('19-24', 'Masculino', 'Sudeste', 'Pop', 'Rap/Trap/Hip Hop, Pagode/Samba, Jazz/Blues', 'Latina/Reggaeton/Dembow/Salsa, Clássica/Instrumental', 'Influência cultural', 'Não me identifico', 'Vários gêneros', 'Menos de 1 hora por dia', 'Spotify, Apple Music e outras plataformas musicais.', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('35-44', 'Feminino', 'Sudeste', 'Sertanejo/Sertanejo Universitário', 'Sertanejo/Sertanejo Universitário', 'Rap/Trap/HipHop, Indie/Alternativo', 'Emoção que transmite', 'Não gosto dos artistas do gênero', 'Vários gêneros', 'Menos de 1 hora por dia', 'Spotify, Apple Music e outras plataformas musicais.', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('35-44', 'Feminino', 'Sudeste', 'Sertanejo/Sertanejo Universitário', 'Sertanejo/Sertanejo Universitário, MPB', 'Funk, Rap/Trap/HipHop', 'Afinidade com artistas do gênero', 'Letra', 'Vários gêneros', 'Menos de 1 hora por dia', 'Amigos/Familiares', 'As vezes', 'Nacionais');
INSERT INTO music_data VALUES ('45+', 'Feminino', 'Centro-Oeste', 'Pop', 'Sertanejo/Sertanejo Universitário', 'Funk', 'Letra', 'Letra', 'Vários gêneros', '2-4 horas', 'Rádio', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('45+', 'Feminino', 'Centro-Oeste', 'Pagode/Samba', 'Sertanejo/Sertanejo Universitário, Pagode/Samba, Jazz/Blues, Clássica/Instrumental', 'Sertanejo/Sertanejo Universitário, Funk, Rap/Trap/HipHop, Rock/Metal, Pop, Eletrônica/Dubstep/Techno/EDM, Gospel/Religiosa, Pagode/Samba, Forró/Piseiro/Brega, Jazz/Blues, Clássica/Instrumental', 'Letra', 'Letra', 'Vários gêneros', '2-4 horas', 'Rádio', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('19-24', 'Feminino', 'Sudeste', 'Rock/Metal', 'Rock/Metal, Pop, MPB, Clássica/Instrumental', 'Sertanejo/Sertanejo Universitário, Funk, Gospel/Religiosa', 'Emoção que transmite', 'Não me identifico', 'Poucos gêneros', '1-2 horas', 'Youtube', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('16-18', 'Feminino', 'Sul', 'Sertanejo/Sertanejo Universitário', 'Sertanejo/Sertanejo Universitário, Funk, Eletrônica/Dubstep/Techno/EDM', 'Rap/Trap/HipHop, Forró/Piseiro/Brega', 'Ritmo/Instrumental/Beat', 'Letra', 'Vários gêneros', 'Mais de 4 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'As vezes', 'Internacionais');
INSERT INTO music_data VALUES ('16-18', 'Feminino', 'Centro-Oeste', 'Pop', 'Funk, Rap/Trap/Hip Hop, Rock/Metal, Pop, Eletrônica/Dubstep/Techno/EDM, MPB, Pagode/Samba, Latina/Reggaeton/Dembow/Salsa, Indie/Alternativo', 'Sertanejo/Sertanejo Universitário, Gospel/Religiosa, Forró/Piseiro/Brega', 'Ritmo/Instrumental/Beat', 'Ritmo/Instrumental/Beat', 'Vários gêneros', 'Mais de 4 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('16-18', 'Masculino', 'Centro-Oeste', 'Gospel/Religiosa', 'Pop, Gospel/Religiosa, MPB, Indie/Alternativo', 'Sertanejo/Sertanejo Universitário, Funk, Rap/Trap/HipHop, Eletrônica/Dubstep/Techno/EDM, Latina/Reggaeton/Dembow/Salsa, Forró/Piseiro/Brega', 'Ritmo/Instrumental/Beat', 'Letra', 'Poucos gêneros', '1-2 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'Frequentemente', 'Ambos');
INSERT INTO music_data VALUES ('16-18', 'Feminino', 'Centro-Oeste', 'Sertanejo/Sertanejo Universitário', 'Sertanejo/Sertanejo Universitário, Funk, Rap/Trap/Hip Hop, Eletrônica/Dubstep/Techno/EDM, Pagode/Samba, Latina/Reggaeton/Dembow/Salsa, Forró/Piseiro/Brega', 'Gospel/Religiosa, MPB, Indie/Alternativo, Jazz/Blues', 'Ritmo/Instrumental/Beat', 'Não me identifico', 'Vários gêneros', '2-4 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'Frequentemente', 'Ambos');
INSERT INTO music_data VALUES ('15 anos ou menos', 'Feminino', 'Sudeste', 'Rock/Metal', 'Rock/Metal, Pop, Indie/Alternativo', 'Gospel/Religiosa, Forró/Piseiro/Brega, Clássica/Instrumental', 'Emoção que transmite', 'Não me identifico', 'Vários gêneros', '1-2 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'Frequentemente', 'Internacionais');
INSERT INTO music_data VALUES ('35-44', 'Feminino', 'Sudeste', 'Rock/Metal', 'Rock/Metal, Eletrônica/Dubstep/Techno/EDM, MPB, Latina/Reggaeton/Dembow/Salsa, Indie/Alternativo, Jazz/Blues, Clássica/Instrumental', 'Funk', 'Ritmo/Instrumental/Beat', 'Letra', 'Vários gêneros', '2-4 horas', 'Youtube', 'Frequentemente', 'Ambos');
INSERT INTO music_data VALUES ('45+', 'Feminino', 'Sudeste', 'MPB', 'Sertanejo/Sertanejo Universitário, Gospel/Religiosa, MPB, Pagode/Samba, Forró/Piseiro/Brega, Jazz/Blues, Clássica/Instrumental', 'Funk, Rock/Metal, Eletrônica/Dubstep/Techno/EDM', 'Emoção que transmite', 'Letra', 'Vários gêneros', 'Menos de 1 hora por dia', 'Amigos/Familiares', 'Frequentemente', 'Ambos');
INSERT INTO music_data VALUES ('16-18', 'Feminino', 'Centro-Oeste', 'Pop', 'Sertanejo/Sertanejo Universitário, Rap/Trap/Hip Hop, Rock/Metal, Pop, Gospel/Religiosa, MPB, Pagode/Samba, Latina/Reggaeton/Dembow/Salsa, Indie/Alternativo', 'Funk, Rock/Metal', 'Ritmo/Instrumental/Beat', 'Não me identifico', 'Vários gêneros', 'Mais de 4 horas', 'Tiktok', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('45+', 'Feminino', 'Centro-Oeste', 'MPB', 'Gospel/Religiosa, MPB, Clássica/Instrumental', 'Sertanejo/Sertanejo Universitário, Funk, Rap/Trap/HipHop, Forró/Piseiro/Brega', 'Letra', 'Letra', 'Poucos gêneros', 'Menos de 1 hora por dia', 'Youtube', 'Raramente', 'Nacionais');
INSERT INTO music_data VALUES ('16-18', 'Feminino', 'Centro-Oeste', 'Indie/Alternativo', 'Sertanejo/Sertanejo Universitário, Rock/Metal, Pop, MPB, Indie/Alternativo', 'Gospel/Religiosa', 'Ritmo/Instrumental/Beat', 'Não me identifico', 'Vários gêneros', '1-2 horas', 'Amigos/Familiares', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('16-18', 'Feminino', 'Centro-Oeste', 'Indie/Alternativo', 'Funk, Rap/Trap/Hip Hop, Rock/Metal, Pop, Indie/Alternativo', 'Sertanejo/Sertanejo Universitário, Gospel/Religiosa', 'Ritmo/Instrumental/Beat', 'Influência religiosa', 'Vários gêneros', '1-2 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'Frequentemente', 'Ambos');
INSERT INTO music_data VALUES ('25-34', 'Feminino', 'Sudeste', 'Forró/Piseiro/Brega', 'Sertanejo/Sertanejo Universitário, Funk, Gospel/Religiosa, Forró/Piseiro/Brega', 'Rap/Trap/HipHop, Rock/Metal, Pop, Eletrônica/Dubstep/Techno/EDM, MPB, Latina/Reggaeton/Dembow/Salsa, Indie/Alternativo, Jazz/Blues', 'Ritmo/Instrumental/Beat', 'Não me identifico', 'Vários gêneros', 'Menos de 1 hora por dia', 'Tiktok', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('25-34', 'Feminino', 'Centro-Oeste', 'Gospel/Religiosa', 'Sertanejo/Sertanejo Universitário, Eletrônica/Dubstep/Techno/EDM, Pagode/Samba', 'Rock/Metal, Jazz/Blues', 'Influência religiosa', 'Opinião negativa de outras pessoas', 'Poucos gêneros', 'Menos de 1 hora por dia', 'Igreja', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('25-34', 'Masculino', 'Centro-Oeste', 'Sertanejo/Sertanejo Universitário', 'Gospel/Religiosa, Pagode/Samba, Forró/Piseiro/Brega', 'Indie/Alternativo, Jazz/Blues, Clássica/Instrumental', 'Influência cultural', 'Não me identifico', 'Poucos gêneros', '1-2 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'As vezes', 'Nacionais');
INSERT INTO music_data VALUES ('45+', 'Feminino', 'Sul', 'Gospel/Religiosa', 'Gospel/Religiosa, MPB', 'Funk, Rap/Trap/HipHop', 'Letra', 'Letra', 'Poucos gêneros', 'Menos de 1 hora por dia', 'Amigos/Familiares', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('45+', 'Feminino', 'Centro-Oeste', 'Gospel/Religiosa', 'Gospel/Religiosa, Clássica/Instrumental', 'Funk, Rap/Trap/HipHop, Rock/Metal, Eletrônica/Dubstep/Techno/EDM', 'Letra', 'Não me identifico', 'Vários gêneros', 'Menos de 1 hora por dia', 'Spotify, Apple Music e outras plataformas musicais.', 'Frequentemente', 'Ambos');
INSERT INTO music_data VALUES ('45+', 'Masculino', 'Sudeste', 'Gospel/Religiosa', 'Sertanejo/Sertanejo Universitário, Gospel/Religiosa', 'Funk, Rap/Trap/HipHop, Rock/Metal, Pop, Eletrônica/Dubstep/Techno/EDM, Latina/Reggaeton/Dembow/Salsa, Indie/Alternativo', 'Influência religiosa', 'Letra', 'Poucos gêneros', 'Menos de 1 hora por dia', 'Spotify, Apple Music e outras plataformas musicais.', 'Nunca', 'Nacionais');
INSERT INTO music_data VALUES ('45+', 'Feminino', 'Centro-Oeste', 'Gospel/Religiosa', 'Gospel/Religiosa', 'Funk, Rap/Trap/HipHop, Rock/Metal', 'Letra', 'Letra', 'Vários gêneros', 'Menos de 1 hora por dia', 'Amigos/Familiares', 'Raramente', 'Nacionais');
INSERT INTO music_data VALUES ('35-44', 'Masculino', 'Centro-Oeste', 'Rock/Metal', 'Sertanejo/Sertanejo Universitário, Rock/Metal, Pop, MPB, Pagode/Samba, Latina/Reggaeton/Dembow/Salsa, Indie/Alternativo, Jazz/Blues', 'Funk, Rap/Trap/HipHop', 'Emoção que transmite', 'Letra', 'Vários gêneros', '1-2 horas', 'Rádio', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('45+', 'Masculino', 'Sudeste', 'MPB', 'Sertanejo/Sertanejo Universitário, MPB', 'Funk, Rap/Trap/HipHop', 'Letra', 'Ritmo/Instrumental/Beat', 'Poucos gêneros', 'Menos de 1 hora por dia', 'Rádio', 'Raramente', 'Nacionais');
INSERT INTO music_data VALUES ('45+', 'Masculino', 'Centro-Oeste', 'Gospel/Religiosa', 'Gospel/Religiosa', 'Funk, Rap/Trap/HipHop, Rock/Metal, Eletrônica/Dubstep/Techno/EDM', 'Influência religiosa', 'Letra', 'Apenas um gênero', '2-4 horas', 'Youtube', 'Raramente', 'Ambos');
INSERT INTO music_data VALUES ('45+', 'Feminino', 'Sudeste', 'Gospel/Religiosa', 'Gospel/Religiosa', 'Funk', 'Letra', 'Letra', 'Poucos gêneros', 'Menos de 1 hora por dia', 'Youtube', 'As vezes', 'Nacionais');
INSERT INTO music_data VALUES ('45+', 'Masculino', 'Sudeste', 'Gospel/Religiosa', 'Gospel/Religiosa', 'Sertanejo/Sertanejo Universitário, Funk, Rap/Trap/HipHop, Rock/Metal, Pop, Eletrônica/Dubstep/Techno/EDM, MPB, Pagode/Samba, Latina/Reggaeton/Dembow/Salsa, Forró/Piseiro/Brega, Indie/Alternativo, Jazz/Blues', 'Letra', 'Letra', 'Apenas um gênero', '1-2 horas', 'Igreja ', 'Raramente', 'Nacionais');
INSERT INTO music_data VALUES ('45+', 'Masculino', 'Centro-Oeste', 'Gospel/Religiosa', 'Gospel/Religiosa', 'Sertanejo/Sertanejo Universitário, Funk, Rap/Trap/HipHop, Rock/Metal, Pop, Eletrônica/Dubstep/Techno/EDM, MPB, Pagode/Samba, Latina/Reggaeton/Dembow/Salsa, Forró/Piseiro/Brega, Indie/Alternativo, Clássica/Instrumental', 'Influência religiosa', 'Não me identifico', 'Apenas um gênero', 'Menos de 1 hora por dia', 'Youtube', 'As vezes', 'Ambos');
INSERT INTO music_data VALUES ('45+', 'Masculino', 'Centro-Oeste', 'Eletrônica/Dubstep/Techno/EDM', 'Eletrônica/Dubstep/Techno/EDM', 'Funk, Rap/Trap/HipHop', 'Ritmo/Instrumental/Beat', 'Letra', 'Vários gêneros', '1-2 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'Frequentemente', 'Ambos');
INSERT INTO music_data VALUES ('45+', 'Feminino', 'Centro-Oeste', 'Gospel/Religiosa', 'Gospel/Religiosa', 'Sertanejo/Sertanejo Universitário, Funk, Rap/Trap/HipHop, Rock/Metal, Eletrônica/Dubstep/Techno/EDM, Pagode/Samba, Latina/Reggaeton/Dembow/Salsa, Forró/Piseiro/Brega, Indie/Alternativo, Jazz/Blues', 'Letra', 'Letra', 'Poucos gêneros', '1-2 horas', 'Spotify, Apple Music e outras plataformas musicais.', 'As vezes', 'Ambos');